### ISSUE TITLE
The ability to create checkpoints

### ISSUE THREAD

**Issue by gamingdevotee** [LSBUGPG/UnityLibrary#13]

**Comment by gamingdevotee** [comment]
@notleeandrew please describe this in more detail.

**Comment by gamingdevotee** [comment]
This includes two separate codes, the first is the actual checkpoint code. 

The stuff below here is one script that you attach to the checkpoint itself

using UnityEngine;
using System.Collections;

public class Checkpoint : MonoBehaviour 
{
    void OnTriggerEnter(Collider Col)
    {
        if (!Col.CompareTag ("Player"))
            return;

```
    PlayerController PC = Col.GetComponent<PlayerController> ();
    PC.RespawnPosition = transform.position;

    //Save Position
    PlayerPrefs.SetFloat("PosX", transform.position.x);
    PlayerPrefs.SetFloat("PosY", transform.position.y);
    PlayerPrefs.SetFloat("PosZ", transform.position.z);
    PlayerPrefs.Save ();
}
```

}

**Comment by gamingdevotee** [comment]
This second code is what you attach to the player.

using UnityEngine;
using System.Collections;

public class PlayerController : MonoBehaviour 
{
    public Vector3 RespawnPosition = Vector3.zero;

```
// Use this for initialization
void Start () 
{
    float x = PlayerPrefs.GetFloat ("PosX", transform.position.x);
    float y = PlayerPrefs.GetFloat ("PosY", transform.position.y);
    float z = PlayerPrefs.GetFloat ("PosZ", transform.position.z);

    //Get start position
    RespawnPosition = new Vector3(x, y, z);

    Respawn ();
}

public void Respawn()
{
    transform.position = RespawnPosition;
}

void Update()
{
    if (Input.GetKeyDown (KeyCode.Space)) 
        Respawn ();

}
```

}

**Comment by gamingdevotee** [comment]
This code will also allow you to save your game by saving it to the registry. I hope I have laid this out okay, never done this before XD

**Comment by gamingdevotee** [comment]
Oh and don't forget to set the checkpoint's rigidbody to ontriggerenter. And remember to make sure the player is tagged. Alan showed me how to do it so it definitely should work, and we have tested it so it should definitely should work!

**Comment by paulsinnett** [comment]
@gamingdevotee I like this idea as it represents a generally useful component which many of might want to use in our projects. But I think this should be two or more components that work together to achieve this. In your example you have the checkpoint stored in the PlayerPrefs which means that this is also a save game component. Ideally I think we'd want to separate out save game data from checkpoints.

What do you think?

**Comment by gamingdevotee** [comment]
Ah I understand what you mean, sorry I haven't replied sooner. I don't actually know too much about save points, but I do realise that maybe a good way of solving this issue besides deleting the code that allows the player to save off the checkpoint, but is there some way of making that code function from an actual save point? Such as using the code on a prefab labelled save point?

Oh and about Tom's component that is in review about the player movement. I have code that could solve that issue so can I take it if it still hasn't been solved?
