### ISSUE TITLE
Safe zones where enemies cannot enter

### ISSUE THREAD

**Issue by notleeandrew** [LSBUGPG/UnityLibrary#41]
I want there to be a zone where the player is completely safe from enemies

**Comment by gamingdevotee** [comment]
This code will prevent enemies to enter it, but they will keep walking into the box collider. So you might have to add stuff should you wish for them to stop or turn idle.

using UnityEngine;
using System.Collections;

public class SafeZone : MonoBehaviour {
    public GameObject player;
    void Start(){
        Physics.IgnoreCollision (gameObject.GetComponent<Collider> (), player.GetComponent<Collider> ());
    }

}
